# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Cada "-" sería un step...
      - uses: actions/checkout@v2
        name: actions checkout exectution
      
      # Esta sería la forma "correcta" de definir un step que hace varias cosas en UN run multilinea
      - name: (2) run npm install and build
        run: |
          npm install
          npm run build

      # Sube archivos generados en este job (de su VM)
      - uses: actions/upload-artifact@master
        with:
            name: webpack artifacts
            path: public/
      
    
  tests:
    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      matrix:
        os: [windows-2016, ubuntu-20.04]
        node-version: [10.x, 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    # Descarga archivos generados en este job (de su VM)
    # Pareciera ser que el orden afecta a la descarga del artifact. Primero necesita hacer checkout. OJO
    - uses: actions/download-artifact@master
      with:
        name: webpack artifacts
        path: public

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # npm ci es equivalente a "npm install" solo que no actualiza el package-lock y necesita si o si ese file o explota
    - name: npm install & test
      run: |
        npm install
        npm test
      # ¿Para qué es ésto del environment CI:true?
      env:
        CI: true
